### ISSUE TITLE
Create workflow for running Java tests, etc.

### ISSUE THREAD

**Issue by L00161836** [ruthlennonatu/rogue22#31]
Example .yaml file is now added to pipeline branch.

To do: Finish .yaml file to allow for building of Java environment and run test against class.

Dylan has created a much more optimised workflow for running Java code. - Mark

**Comment by L00161836** [comment]
I had a look at Dylan's wip branch there, looks like some good stuff. 

How do you feel about it at the moment Dylan? Do you think it needs more work before merging?

**Comment by ghost** [comment]
I have amended the file to facilitate automated JUnit testing rather than just automated java maven builds. Please note it requires the Junit dependency to be defined in the pom.xml file within the Java project.

**Comment by L00161836** [comment]
That's great Dylan, looks like it's all chugging along nicely.

Do you need some Java code to test the workflow out on?

**Comment by ghost** [comment]
I've tested it myself in a private repository and it seems* to work okay but yes there will need to be a java maven project with a pom.xml file pushed for it to work. Wasn't sure whether the team handling the code aspect would be pushing their projects up or not.
