### ISSUE TITLE
Identify performance management tool(s) required for the project

### ISSUE THREAD

**Issue by ghost** [ruthlennonatu/rogue22#42]
### Description
Identify performance management tools that will allow the team to ensure the product meets the performance and reliability requirements of the customer. With future sprints, these tool(s) will help identify if performance is improving or degrading and subsequently, allow the team to address this if needs be.

### Definition of Ready
A Java project should be pushed and readily available to test performance management tools on.

### Definition of Done
Current performance of the working Java project should be verified as optimal or below expectations.

**Comment by ghost** [comment]
I think I may close this issue as it has been addressed in 79e6494bcbec31f888d80d3ba33a2f87fbf56429 and f05c2867864dcaf4cf82198993f7713d158206fb as well as the information Mark provided on slack if that sounds okay? @L00148698-tasha @L00161836

**Comment by L00161836** [comment]
Yeah that's no problem Dylan.

**Comment by L00148698-tasha** [comment]
Yeah, that sounds good

Natasha

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ghost** [comment]
Closed as addressed by @L00148698-tasha , @L00163199  and @L00161836  in 79e6494bcbec31f888d80d3ba33a2f87fbf56429, f05c2867864dcaf4cf82198993f7713d158206fb and on slack
